CREATE TABLE `AN_TUNE_ACCESS` (
  `ACCESS_SEQ` bigint(20) NOT NULL AUTO_INCREMENT,
  `IP` varchar(100) DEFAULT NULL,
  `MAC_ADDR` varchar(100) DEFAULT NULL,
  `REG_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ACCESS_SEQ`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8