CREATE TABLE `AN_TUNE_USAGE` (
  `USAGE_SEQ` bigint(20) NOT NULL AUTO_INCREMENT,
  `USER_ID` varchar(100) DEFAULT NULL,
  `REG_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`USAGE_SEQ`),
  KEY `AN_TUNE_PRG_FK` (`USER_ID`),
  CONSTRAINT `AN_TUNE_PRG_FK` FOREIGN KEY (`USER_ID`) REFERENCES `AN_USER` (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1656 DEFAULT CHARSET=utf8